config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :searches
  root "homepage#landing"
  get "/countries" , to: "homepage#countries"
  get "/show_result" , to: "homepage#show_result"
  post "/result" , to: "homepage#get_result"
  post "/weather" , to: "homepage#weather"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
primary_abstract_class
require 'rest-client'
  class << self

    # Fetch list of all countries from restcountries.com
        def countries
              @countries = []
              url = "https://restcountries.com/v2/all"
              @responce = RestClient.get(url)
              @res = JSON.parse(@responce.body)    
                @res.each do |k,v|
                    @countries.push(k["name"])
                end
              return @countries
        end

  #  Fetch opensource weather API for Weather details
        def get_result val
              url = "https://api.openweathermap.org/data/2.5/weather?appid=0023401ec97a392619e841c35220143c&q=#{val}"
              res_weather = RestClient.get(url)
              @res_weather = JSON.parse(res_weather.body)
              Search.create(body: val)
              return @res_weather
        end

  # Convert temp into Celcius 
        def into_celcius val
              return val.to_i - 273
        end
  end
end

app/models/search.rb
class Search < ApplicationRecord
    validates :body , presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
    require 'rest-client'

# Application root page 123
    def landing
    end   

# Method for get weather detail and pass data to show_result
    def weather
        if params[:sessions][:body].present?
          @result = ApplicationRecord.get_result(params[:sessions][:body]);
         if @result.present?
             redirect_to show_result_path(@result)
         end
        end
    end

# Method for getting the result and show the result in show template 
    def show_result
        @result = params
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/homepage/landing.html.erb
<br><br><br><br><br>
    <figure class="text-center">
    <%= image_tag "weather-logo.png" , class: "image-size" %>
    <blockquote class="blockquote">
      <p>Wherever you go, no matter what the weather, always bring your own sunshine</p>
    </blockquote>
    <figcaption class="blockquote-footer">
          Awesome <cite title="Source Title">Weather</cite>
    </figcaption>
</figure>


<div class = "center" >
      <button type="button" class="btn btn-primary position-relative" id ="click">
        Get Started
        <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cloud-drizzle-fill" viewBox="0 0 16 16">
        <path d="M4.158 12.025a.5.5 0 0 1 .316.633l-.5 1.5a.5.5 0 0 1-.948-.316l.5-1.5a.5.5 0 0 1 .632-.317zm6 0a.5.5 0 0 1 .316.633l-.5 1.5a.5.5 0 0 1-.948-.316l.5-1.5a.5.5 0 0 1 .632-.317zm-3.5 1.5a.5.5 0 0 1 .316.633l-.5 1.5a.5.5 0 0 1-.948-.316l.5-1.5a.5.5 0 0 1 .632-.317zm6 0a.5.5 0 0 1 .316.633l-.5 1.5a.5.5 0 1 1-.948-.316l.5-1.5a.5.5 0 0 1 .632-.317zm.747-8.498a5.001 5.001 0 0 0-9.499-1.004A3.5 3.5 0 1 0 3.5 11H13a3 3 0 0 0 .405-5.973z"/>
      </svg>
          <span class="visually-hidden">unread messages</span>
        </span>
      </button>
</div>

<div class="open">
    <%= form_for :sessions , url: weather_path do |s|%>
        <p class = "center">
        <%= s.select :body, ApplicationRecord.countries %>
        <%= s.submit "Search" , class: "btn btn-primary btn-sm" , id: "me" %>
        </p>
    <%end%>
 </div>
 <p id="img" class= "centerr"><%= image_tag 'load3.svg' %></p>
<script>
  $(document).ready(function(){
    $("#img").hide();
    $(".open").hide()
    $("#click").click(function(){
      $("#click").hide();
      $(".open").slideDown();
    })
$("#me").click(function(){
  $("#img").css("display","block");

})
  })
</script>
<style>
.centerr {
  width: 100%;
  -webkit-transform: translateX(-50%) translateY(-50%);
  transform: translateX(-50%) translateY(-50%);
  position: absolute; /*or fixed*/
  left: 50%;
  top: 50%;
  text-align: center;
}
</style>

app/views/homepage/show_result.html.erb
<div class = "center-content" >
<div class="card" style="width: 20rem;">
<% if @result["weather"][0]["main"].downcase == "clouds" %>
  <%= image_tag "cloudy.jpeg" , class: "card-img-top"  %>
<% elsif  @result["weather"][0]["main"].downcase == "rain" %>
<%= image_tag "rainy.webp" , class: "card-img-top"  %>
<% elsif  @result["weather"][0]["main"].downcase == "clear" %>
<%= image_tag "clear.jpeg" , class: "card-img-top"  %>
<% elsif  @result["weather"][0]["main"].downcase == "sunny" %>
<%= image_tag "sunny.jpeg" , class: "card-img-top"  %>
<% elsif  @result["weather"][0]["main"].downcase == "thunderstorm" %>
<%= image_tag "thunder.jpeg" , class: "card-img-top"  %>
<% elsif  @result["weather"][0]["main"].downcase == "snow" %>
<%= image_tag "snow.jpeg" , class: "card-img-top"  %>
  <% end %>
  <div class="card-body">
    <h5 class="card-title">Weather Detail</h5>
   <%= Time.now.strftime("%B %e, %Y - %A ") %>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Counry: <strong> <%= @result["name"] %> </strong></li>
    <li class="list-group-item">Condition: <strong> <%= @result["weather"][0]["main"] %></strong></li>
    <li class="list-group-item">Temperature: <strong> <%= ApplicationRecord.into_celcius(@result["main"]["temp"]) %> C </strong></li>
    <li class="list-group-item">Humidity: <strong> <%= @result["main"]["humidity"] %>%</strong></li>
    <li class="list-group-item">Wind Speed: <strong> <%= @result["wind"]["speed"] %></strong></li>
  </ul>
  <div class="card-body">
  <%= link_to "Back" , :back , class: "btn btn-primary btn-sm" %>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AwesomeWeather</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <link href="/your-path-to-uicons/css/uicons-[your-style].css" rel="stylesheet">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>